import type { AgentTrustReport, ScoreCategory } from "./types.ts";

function categoryLines(label: string, category: ScoreCategory | undefined) {
  if (!category) return [`### ${label}`, "", "Not evaluated.", ""];
  return [
    `### ${label}`,
    "",
    `- Score: ${category.score === null ? "Not scored" : `${category.score}/100`}`,
    `- Confidence: ${category.confidence}`,
    `- Evidence items: ${category.evidenceCount}`,
    `- Summary: ${category.summary}`,
    "",
  ];
}
function bulletList(items: string[], fallback: string) {
  return items.length
    ? items.map((item) => `- ${item}`)
    : [`- ${fallback}`];
}

export function formatAgentTrustReportAsMarkdown(
  report: AgentTrustReport,
) {
  const score = report.trustScore;
  return [
    "# Veyra Agent Trust Report",
    "",
    `**Report ID:** \`${report.reportId}\`  `,
    `**Subject:** ${report.subject.name}  `,
    `**Trust status:** \`${score.status}\`  `,
    `**Trust Score:** ${score.overall === null ? "Limited data" : `${score.overall}/100`}  `,
    `**Arc verification:** \`${report.verification.status}\`  `,
    `**Generated at:** ${report.generatedAt}`,
    "",
    "## Executive Summary",
    "",
    ...report.executiveSummary.map((line) => `${line}`),
    "",
    "## Trust Score Breakdown",
    "",
    ...categoryLines("Code Health", score.categories.codeHealth),
    ...categoryLines("Agent Identity", score.categories.agentIdentity),
    ...categoryLines(
      "Execution Reliability",
      score.categories.executionReliability,
    ),
    ...categoryLines("Payment History", score.categories.paymentHistory),
    ...categoryLines("Service Reliability", score.categories.serviceReliability),
    ...categoryLines(
      "Contract Transparency",
      score.categories.contractTransparency,
    ),
    "## Agent Identity",
    "",
    "```json",
    JSON.stringify(report.identity, null, 2),
    "```",
    "",
    "## Code & Project Intelligence",
    "",
    report.codeIntelligence.repository
      ? `Repository: [${report.codeIntelligence.repository.fullName}](${report.codeIntelligence.repository.canonicalUrl})`
      : "Repository intelligence was not provided.",
    "",
    "## Execution Reliability",
    "",
    "```json",
    JSON.stringify(report.executionReliability, null, 2),
    "```",
    "",
    "## Payments & Receipts",
    "",
    "```json",
    JSON.stringify(report.paymentsAndReceipts, null, 2),
    "```",
    "",
    "## Services",
    "",
    "```json",
    JSON.stringify(report.services, null, 2),
    "```",
    "",
    "## Contract Transparency Snapshot",
    "",
    "```json",
    JSON.stringify(report.contractTransparency, null, 2),
    "```",
    "",
    "## Endpoint Availability Snapshot",
    "",
    "```json",
    JSON.stringify(report.endpointAvailability, null, 2),
    "```",
    "",
    "## Arc USDC Compliance",
    "",
    "```json",
    JSON.stringify(report.arcCompliance ?? { status: "not_provided" }, null, 2),
    "```",
    "",
    "## Evidence-Backed Strengths",
    "",
    ...bulletList(
      report.evidenceBackedStrengths.map((item) => item.detail),
      "No positive signal was inferred without supporting evidence.",
    ),
    "",
    "## Risks & Review Items",
    "",
    ...bulletList(
      report.risksAndReviewItems.map((item) => item.detail),
      "No material review item was identified in the collected evidence.",
    ),
    "",
    "## Questions Before Integration",
    "",
    ...bulletList(report.questionsBeforeIntegration, "Independent review is required."),
    "",
    "## Evidence & Data Freshness",
    "",
    ...report.dataFreshness.map(
      (item) =>
        `- ${item.source}: ${item.fetchedAt} · ${item.cacheMode} · ${item.upstreamStatus}`,
    ),
    "",
    "## Limitations",
    "",
    ...bulletList(report.limitations, "No limitations recorded."),
    "",
    "<details>",
    "<summary>Payment & Verification Details</summary>",
    "",
    `Report hash: \`${report.verification.reportHash}\``,
    "",
    ...bulletList(
      report.verification.proofs.map(
        (proof) =>
          `${proof.receiptId}: ${proof.status}${proof.transactionHash ? ` · ${proof.transactionHash}` : ""}`,
      ),
      "Verification pending or no receipt proofs recorded.",
    ),
    "",
    "</details>",
    "",
    "Generated by Veyra.",
    "",
  ].join("\n");
}
